### ISSUE TITLE
CollisionManager Bug

### ISSUE THREAD

**Issue by SirGlozz** [VolmitSoftware/VehiclesPlus#57]
**Describe the bug**  
When a player try to drive any vehicle starts to lag (default and custom vehicles), a seconds later, the server disconnects the player saying "Timed out".

**To Reproduce**  
1. Enter a vehicle
2. When you try to go forward, the vehicle moves a little bit
3. The vehicle starts to lag and stop moving
4. Error:
> [19:08:13 WARN]: [VehiclesPlusPro] Task #375 for VehiclesPlusPro v2.1.0 generated an exception
java.lang.NullPointerException: null
        at me.legofreak107.vehiclesplus.vehicles.managers.CollisionManager.calculateHitbox(CollisionManager.java:88) ~[?:?]
        at me.legofreak107.vehiclesplus.vehicles.managers.CollisionManager.checkCollision(CollisionManager.java:102) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]
        at java.lang.Thread.run(Thread.java:830) [?:?]

5. The server disconnect the player with the "Timed out" screen.

**Expected behavior**  
I think the bug started when i updated VehiclesPlus to the version 2.1.0.
When i use 2.0.10 version of VehiclesPlus with the same plugins, server platform and version, i don't have problems
I set the complete Hitbox to 0 and vehicles starts going fine, but they don't have collisions, so I thought it would be a collision problem.

**Server and Plugin Information**  
 - Installed plugins: 
![image](https://user-images.githubusercontent.com/77519944/105251537-81ee6280-5b5a-11eb-8e24-4e521053fe29.png)

 - VehiclesPlus Version: 2.1.0
 - VehiclesPlusPro
 - Server Platform and Version: PaperSpigot 1.14.4 #243
 - Operating System (if applicable): Server host

**Comment by stijnb1234** [comment]
Please check if latest version still has this issue, and reopen if it does.
